export const AllSoulBeast = {
  "Keth Stalker": {
    name: "Keth Stalker",
    title: "Crystal Nightmare Hunter",
    composition: {
      frost: 30,
      demon: 40,
      water: 30,
    },
    abilities: [
      {
        name: "Nightmare Frost",
        emoji: "❄️",
        type: "quick",
        cooldown: 3,
        damage: 18,
        effect: "Applies slow for 2 seconds",
        description: "Channels demonic frost to slow and damage enemies",
        target: "single-enemy",
        castTime: 0.8,
      },
      {
        name: "Crystal Prison",
        emoji: "💎",
        type: "power",
        cooldown: 8,
        damage: 25,
        effect: "Stuns target for 1.5 seconds",
        description: "Traps enemy in crystalline ice, preventing movement",
        target: "single-enemy",
        castTime: 2.0,
      },
      {
        name: "Abyssal Tide",
        emoji: "🌊",
        type: "power",
        cooldown: 10,
        damage: 35,
        effect: "Heals self for 15 HP",
        description:
          "Summons dark waters that damage foes and restore vitality",
        initiationTime: 3,
        target: "all-enemy",
        castTime: 2.2,
      },
      {
        name: "Nightmare Hunt",
        emoji: "🏹",
        type: "ultimate",
        cooldown: 25,
        damage: 60,
        effect: "Next 2 abilities have 50% reduced cooldown",
        description: "Enters a hunting frenzy, unleashing rapid attacks",
        initiationTime: 8,
        target: "single-enemy",
        castTime: 3.5,
      },
    ],
  },
  "Crimson Vorthak": {
    name: "Crimson Vorthak",
    title: "Bleeding Rose Executioner",
    composition: {
      fire: 60,
      demon: 30,
      beast: 10,
    },
    abilities: [
      {
        name: "Flame Slash",
        emoji: "🔥",
        type: "quick",
        cooldown: 2,
        damage: 22,
        effect: "Burns for 5 damage over 3 seconds",
        description: "Quick fiery strike that leaves burning wounds",
        target: "single-enemy",
        castTime: 0.6,
      },
      {
        name: "Demonic Roar",
        emoji: "😈",
        type: "power",
        cooldown: 9,
        damage: 15,
        effect: "Reduces enemy damage by 30% for 4 seconds",
        description: "Terrifying howl that weakens enemy resolve",
        target: "all-enemy",
        castTime: 1.8,
      },
      {
        name: "Infernal Execution",
        emoji: "⚔️",
        type: "power",
        cooldown: 12,
        damage: 45,
        effect: "Damage increases by 50% if enemy below 40% HP",
        description: "Devastating finisher attack against wounded foes",
        initiationTime: 4,
        target: "single-enemy",
        castTime: 2.1,
      },
      {
        name: "Rose of Destruction",
        emoji: "🌹",
        type: "ultimate",
        cooldown: 30,
        damage: 70,
        effect: "Creates fire field that deals 10 damage/second for 5 seconds",
        description: "Blooms a deadly rose of fire that burns the battlefield",
        initiationTime: 10,
        target: "all-enemy",
        castTime: 4.0,
      },
    ],
  },
  "Bone Thurak": {
    name: "Bone Thurak",
    title: "Ancient Fire Caller",
    composition: {
      earth: 50,
      fire: 30,
      demon: 20,
    },
    abilities: [
      {
        name: "Stone Shard",
        emoji: "🪨",
        type: "quick",
        cooldown: 3,
        damage: 20,
        effect: "Reduces enemy damage output by 20% for 4 seconds",
        description: "Hurls sharp stone fragments that weaken enemies",
        target: "single-enemy",
        castTime: 0.7,
      },
      {
        name: "Molten Boulder",
        emoji: "🌋",
        type: "power",
        cooldown: 8,
        damage: 40,
        effect: "25% chance to daze enemy, preventing ability use for 1 second",
        description: "Launches a massive burning rock that can stun enemies",
        target: "single-enemy",
        castTime: 2.3,
      },
      {
        name: "Bone Armor",
        emoji: "🦴",
        type: "power",
        cooldown: 8,
        damage: 0,
        effect: "Reduces all damage by 50% for 6 seconds",
        description: "Summons protective bone plating from the earth",
        target: "self",
        castTime: 0,
      },
      {
        name: "Ancient Eruption",
        emoji: "🔴",
        type: "ultimate",
        cooldown: 28,
        damage: 65,
        effect: "Creates 3 lava pools that deal 8 damage/second",
        description: "Calls forth an ancient volcanic eruption",
        initiationTime: 9,
        target: "all-enemy",
        castTime: 3.8,
      },
    ],
  },
  "Shrom Xelar": {
    name: "Shrom Xelar",
    title: "Psychic Mushroom Axelar",
    composition: {
      nature: 60,
      beast: 30,
      demon: 10,
    },
    abilities: [
      {
        name: "Spore Burst",
        emoji: "🌿",
        type: "quick",
        cooldown: 3,
        damage: 20,
        effect: "30% chance to poison for 8 damage over 4 seconds",
        description: "Releases toxic spores from mushroom cap",
        target: "single-enemy",
        castTime: 0.9,
      },
      {
        name: "Mycelium Network",
        emoji: "🕸️",
        type: "power",
        cooldown: 9,
        damage: 28,
        effect: "Spreads to nearby enemies, damage increases per target hit",
        description: "Underground fungal network damages connected foes",
        target: "all-enemy",
        castTime: 2.4,
      },
      {
        name: "Soul Absorb",
        emoji: "😈",
        type: "power",
        cooldown: 12,
        damage: 25,
        effect: "Heals for 100% of damage dealt and gains 20% damage boost",
        description: "Mushroom feeds on enemy soul energy to grow stronger",
        initiationTime: 3,
        target: "single-enemy",
        castTime: 1.9,
      },
      {
        name: "Fungal Nightmare",
        emoji: "🧠",
        type: "ultimate",
        cooldown: 30,
        damage: 70,
        effect:
          "Causes hallucinations, enemy attacks random targets for 6 seconds",
        description: "Psychedelic spores invade enemy mind, causing chaos",
        initiationTime: 12,
        target: "single-enemy",
        castTime: 3.6,
      },
    ],
  },
  "Void Ghorth": {
    name: "Void Ghorth",
    title: "Dimensional Terror Beast",
    composition: {
      water: 50,
      beast: 40,
      demon: 10,
    },
    abilities: [
      {
        name: "Savage Splash",
        emoji: "💦",
        type: "quick",
        cooldown: 3,
        damage: 19,
        effect: "Heals self for 8 HP",
        description: "Bestial attack that splashes healing waters",
        target: "single-enemy",
        castTime: 0.7,
      },
      {
        name: "Dimensional Bite",
        emoji: "🕳️",
        type: "power",
        cooldown: 9,
        damage: 35,
        effect: "Ignores 100% of enemy armor",
        description: "Phases through dimensions to deliver a devastating bite",
        initiationTime: 3,
        target: "single-enemy",
        castTime: 2.1,
      },
      {
        name: "Terror Howl",
        emoji: "😱",
        type: "power",
        cooldown: 11,
        damage: 20,
        effect: "Reduces enemy damage output by 50% for 3 seconds",
        description: "Horrifying roar that terrifies and weakens enemies",
        target: "all-enemy",
        castTime: 1.7,
      },
      {
        name: "Void Tsunami",
        emoji: "🌊",
        type: "ultimate",
        cooldown: 26,
        damage: 75,
        effect: "Creates void zones that deal 12 damage/second",
        description: "Summons dimensional water that tears reality apart",
        initiationTime: 10,
        target: "all-enemy",
        castTime: 3.2,
      },
    ],
  },
  "Deep Zephyros": {
    name: "Deep Zephyros",
    title: "Abyssal Mind Breaker",
    composition: {
      water: 40,
      beast: 30,
      demon: 30,
    },
    abilities: [
      {
        name: "Mind Lash",
        emoji: "🧠",
        type: "quick",
        cooldown: 3,
        damage: 20,
        effect: "Reduces enemy accuracy by 25% for 4 seconds",
        description: "Psychic attack that disrupts enemy focus",
        target: "single-enemy",
        castTime: 0.8,
      },
      {
        name: "Bestial Surge",
        emoji: "😈",
        type: "power",
        cooldown: 8,
        damage: 35,
        effect: "Reduces ability cooldowns by 20% for 5 seconds",
        description: "Channels primal instincts for rapid ability casting",
        target: "self",
        castTime: 1.6,
      },
      {
        name: "Abyssal Drain",
        emoji: "🩸",
        type: "power",
        cooldown: 10,
        damage: 32,
        effect: "Steals 20 HP from enemy",
        description: "Drains life force through demonic waters",
        initiationTime: 3,
        target: "single-enemy",
        castTime: 2.0,
      },
      {
        name: "Mind Break",
        emoji: "💥",
        type: "ultimate",
        cooldown: 24,
        damage: 65,
        effect: "Enemy abilities have double cooldown for 8 seconds",
        description: "Shatters enemy psyche, disrupting their abilities",
        initiationTime: 8,
        target: "single-enemy",
        castTime: 3.4,
      },
    ],
  },
  Astrix: {
    name: "Astrix",
    title: "Starbound Void Walker",
    composition: {
      demon: 40,
      divine: 30,
      wind: 30,
    },
    abilities: [
      {
        name: "Void Wind",
        emoji: "💨",
        type: "quick",
        cooldown: 2,
        damage: 21,
        effect: "Ignores 100% of enemy armor",
        description: "Wind infused with void energy that bypasses armor",
        target: "single-enemy",
        castTime: 0.9,
      },
      {
        name: "Divine Punishment",
        emoji: "⚡",
        type: "power",
        cooldown: 9,
        damage: 38,
        effect: "+100% damage vs demon enemies",
        description: "Holy power that especially harms demonic foes",
        initiationTime: 3,
        target: "single-enemy",
        castTime: 1.6,
      },
      {
        name: "Stellar Dash",
        emoji: "⭐",
        type: "power",
        cooldown: 7,
        damage: 25,
        effect: "Becomes invulnerable during cast",
        description: "Dashes at light speed, avoiding all attacks",
        target: "single-enemy",
        castTime: 2.1,
      },
      {
        name: "Paradox Storm",
        emoji: "🌀",
        type: "ultimate",
        cooldown: 29,
        damage: 65,
        effect: "Deals divine damage to demons, demon damage to divine",
        description: "Creates a storm of contradictory energies",
        initiationTime: 12,
        target: "all-enemy",
        castTime: 3.2,
      },
    ],
  },
  "Ember Pyrrak": {
    name: "Ember Pyrrak",
    title: "Molten Dawn Herald",
    composition: {
      fire: 80,
      earth: 10,
      beast: 10,
    },
    abilities: [
      {
        name: "Flame Burst",
        emoji: "🔥",
        type: "quick",
        cooldown: 2,
        damage: 26,
        effect: "Burns for 4 damage over 4 seconds",
        description: "Pure fire blast that ignites the target",
        target: "single-enemy",
        castTime: 0.9,
      },
      {
        name: "Molten Claw",
        emoji: "🔴",
        type: "power",
        cooldown: 6,
        damage: 42,
        effect: "Melts enemy armor, reducing defense by 40%",
        description: "Bestial claws superheated to melting point",
        initiationTime: 2,
        target: "single-enemy",
        castTime: 1.5,
      },
      {
        name: "Dawn's Embrace",
        emoji: "🌅",
        type: "power",
        cooldown: 14,
        damage: 0,
        effect: "Heals 50 HP over 5 seconds",
        description: "Channels the healing power of dawn's first light",
        target: "self",
        castTime: 1.5,
      },
      {
        name: "Solar Apocalypse",
        emoji: "✨",
        type: "ultimate",
        cooldown: 35,
        damage: 75,
        effect: "Burns all enemies for 8 damage/second for 5 seconds",
        description: "Brings forth the fury of a dying star",
        initiationTime: 15,
        target: "all-enemy",
        castTime: 3.2,
      },
    ],
  },
  "Seraph Valdris": {
    name: "Seraph Valdris",
    title: "Divine Judgment Bearer",
    composition: {
      divine: 70,
      wind: 20,
      nature: 10,
    },
    abilities: [
      {
        name: "Holy Bolt",
        emoji: "✨",
        type: "quick",
        cooldown: 2,
        damage: 23,
        effect: "Heals self for 5 HP",
        description: "Divine energy that harms foes and heals the righteous",
        target: "single-enemy",
        castTime: 0.5,
      },
      {
        name: "Wind of Judgment",
        emoji: "💨",
        type: "power",
        cooldown: 8,
        damage: 35,
        effect: "Removes all enemy buffs",
        description: "Divine wind that strips away false enhancements",
        initiationTime: 3,
        target: "all-enemy",
        castTime: 2.5,
      },
      {
        name: "Nature's Sanctuary",
        emoji: "🛡️",
        type: "power",
        cooldown: 12,
        damage: 0,
        effect: "Reduces damage by 75% for 3 seconds",
        description: "Creates a sacred grove of protection",
        target: "self",
        castTime: 0,
      },
      {
        name: "Final Judgment",
        emoji: "⚖️",
        type: "ultimate",
        cooldown: 30,
        damage: 85,
        effect: "Damage increases based on enemy's missing HP",
        description: "Divine wrath that grows stronger against the wounded",
        initiationTime: 11,
        target: "single-enemy",
        castTime: 3.2,
      },
    ],
  },
  Morthen: {
    name: "Morthen",
    title: "Silent Death Stalker",
    composition: {
      frost: 50,
      beast: 30,
      wind: 20,
    },
    abilities: [
      {
        name: "Frost Bite",
        emoji: "❄️",
        type: "quick",
        cooldown: 3,
        damage: 20,
        effect: "Increases enemy ability cooldowns by 30% for 3 seconds",
        description: "Chilling bite that numbs and slows the target's reflexes",
        target: "single-enemy",
        castTime: 0.8,
      },
      {
        name: "Silent Strike",
        emoji: "💎",
        type: "power",
        cooldown: 7,
        damage: 40,
        effect: "Cannot be dodged or blocked",
        description: "Moves like the wind to deliver an unavoidable strike",
        initiationTime: 2,
        target: "single-enemy",
        castTime: 2.3,
      },
      {
        name: "Predator's Focus",
        emoji: "👁️",
        type: "power",
        cooldown: 11,
        damage: 0,
        effect: "Next ability deals triple damage",
        description: "Focuses hunting instincts for a devastating attack",
        target: "self",
        castTime: 2.3,
      },
      {
        name: "Absolute Zero",
        emoji: "🔮",
        type: "ultimate",
        cooldown: 27,
        damage: 70,
        effect: "Freezes enemy for 3 seconds",
        description:
          "Brings the temperature to absolute zero",
        initiationTime: 10,
        target: "single-enemy",
        castTime: 4,
      },
    ],
  },
  "Stellar Nexath": {
    name: "Stellar Nexath",
    title: "Cosmic Web Dancer",
    composition: {
      divine: 50,
      wind: 30,
      nature: 20,
    },
    abilities: [
      {
        name: "Starlight",
        emoji: "⭐",
        type: "quick",
        cooldown: 2,
        damage: 22,
        effect: "Restores 6 HP",
        description: "Gentle starlight that heals while harming enemies",
        target: "single-enemy",
        castTime: 0.6,
      },
      {
        name: "Cosmic Winds",
        emoji: "💫",
        type: "power",
        cooldown: 8,
        damage: 33,
        effect: "Reduces ability cooldowns by 50% for 8 seconds",
        description: "Rides stellar winds for enhanced agility",
        target: "self",
        castTime: 1.9,
      },
      {
        name: "Life Web",
        emoji: "🕸️",
        type: "power",
        cooldown: 13,
        damage: 15,
        effect: "Connects to enemy, sharing all damage taken",
        description: "Creates a mystical bond that shares pain",
        initiationTime: 4,
        target: "single-enemy",
        castTime: 1.7,
      },
      {
        name: "Galaxy Dance",
        emoji: "🌌",
        type: "ultimate",
        cooldown: 31,
        damage: 60,
        effect: "Hits 5 times over 3 seconds, each hit stronger",
        description: "Dances through space-time, striking multiple times",
        initiationTime: 13,
        target: "single-enemy",
        castTime: 3.8,
      },
    ],
  },
  Moltak: {
    name: "Moltak",
    title: "Burning Steel Titan",
    composition: {
      fire: 60,
      earth: 25,
      demon: 15,
    },
    abilities: [
      {
        name: "Steel Strike",
        emoji: "😱",
        type: "quick",
        cooldown: 3,
        damage: 25,
        effect: "Ignores 50% of enemy armor",
        description: "Molten metal strike that pierces defenses",
        target: "single-enemy",
        castTime: 0.5,
      },
      {
        name: "Forge Strike",
        emoji: "⚔️",
        type: "power",
        cooldown: 9,
        damage: 45,
        effect: "Stuns for 2 seconds",
        description: "Massive double blow that leaves enemies dazed",
        initiationTime: 3,
        target: "single-enemy",
        castTime: 2.5,
      },
      {
        name: "Demon Steel",
        emoji: "🛡️",
        type: "power",
        cooldown: 12,
        damage: 0,
        effect: "Gains 30 armor and reflects 25% damage for 8 seconds",
        description: "Skin becomes like demonic steel, reflecting attacks",
        target: "self",
        castTime: 2.1,
      },
      {
        name: "Molten Titan",
        emoji: "🦴",
        type: "ultimate",
        cooldown: 33,
        damage: 80,
        effect: "+50% damage and HP for 10 seconds",
        description: "Transforms into a colossal burning titan",
        initiationTime: 14,
        target: "self",
        castTime: 3.8,
      },
    ],
  },
  Hexis: {
    name: "Hexis",
    title: "Geometric Chaos Spawn",
    composition: {
      divine: 40,
      demon: 35,
      earth: 25,
    },
    abilities: [
      {
        name: "Chaos Shard",
        emoji: "🔮",
        type: "quick",
        cooldown: 3,
        damage: 19,
        effect: "Random elemental effect each cast",
        description: "Crystalline projectile with unpredictable properties",
        target: "single-enemy",
        castTime: 0.9,
      },
      {
        name: "Divine Corruption",
        emoji: "☠️",
        type: "power",
        cooldown: 10,
        damage: 36,
        effect: "Heals enemy but applies strong poison",
        description: "Twisted blessing that heals before destroying",
        initiationTime: 3,
        target: "single-enemy",
        castTime: 1.7,
      },
      {
        name: "Geometric Prison",
        emoji: "💎",
        type: "power",
        cooldown: 8,
        damage: 20,
        effect: "Traps enemy for 4 seconds",
        description: "Creates an inescapable geometric prison",
        target: "single-enemy",
        castTime: 2,
      },
      {
        name: "Chaos Singularity",
        emoji: "🕳️",
        type: "ultimate",
        cooldown: 28,
        damage: 65,
        effect: "Randomly applies all status effects",
        description: "Creates a point of pure chaos that affects everything",
        initiationTime: 9,
        target: "all-enemy",
        castTime: 4,
      },
    ],
  },
  "Crystal Nerith": {
    name: "Crystal Nerith",
    title: "Sakura Dream Guardian",
    composition: {
      water: 40,
      nature: 35,
      divine: 25,
    },
    abilities: [
      {
        name: "Petal Stream",
        emoji: "⭐",
        type: "quick",
        cooldown: 2,
        damage: 18,
        effect: "Heals 10 HP",
        description: "Gentle stream of water and sakura petals",
        target: "single-enemy",
        castTime: 1,
      },
      {
        name: "Dream Shield",
        emoji: "🛡️",
        type: "power",
        cooldown: 11,
        damage: 0,
        effect: "Absorbs next 60 damage, then heals for absorbed amount",
        description: "Creates a shield that converts damage to healing",
        target: "self",
        castTime: 2,
      },
      {
        name: "Nature's Embrace",
        emoji: "🌿",
        type: "power",
        cooldown: 9,
        damage: 30,
        effect: "Reduces enemy damage output by 40% and heals self over time",
        description: "Vines embrace and weaken the enemy while healing",
        initiationTime: 3,
        target: "single-enemy",
        castTime: 2.3,
      },
      {
        name: "Sakura Storm",
        emoji: "🌌",
        type: "ultimate",
        cooldown: 26,
        damage: 55,
        effect: "Heals 60 HP and cleanses all debuffs",
        description: "Divine sakura petals that heal and purify",
        initiationTime: 8,
        target: "all-enemy",
        castTime: 3.4,
      },
    ],
  },
  Velana: {
    name: "Velana",
    title: "Midnight Garden Keeper",
    composition: {
      nature: 45,
      wind: 30,
      beast: 25,
    },
    abilities: [
      {
        name: "Thorn Whip",
        emoji: "🌿",
        type: "quick",
        cooldown: 3,
        damage: 21,
        effect: "Pulls enemy closer",
        description: "Thorny vine that lashes and drags enemies",
        target: "single-enemy",
        castTime: 0.7,
      },
      {
        name: "Wind Seed",
        emoji: "🌱",
        type: "power",
        cooldown: 7,
        damage: 28,
        effect: "Plants grow over 5 seconds, dealing damage each second",
        description: "Seeds carried by wind that grow into damaging plants",
        target: "single-enemy",
        castTime: 1.5,
      },
      {
        name: "Feral Instinct",
        emoji: "⚡",
        type: "power",
        cooldown: 12,
        damage: 0,
        effect: "Next 3 abilities have 50% reduced cooldown",
        description: "Awakens primal instincts for rapid ability use",
        target: "self",
        castTime: 1.6,
      },
      {
        name: "Midnight Bloom",
        emoji: "🌙",
        type: "ultimate",
        cooldown: 29,
        damage: 65,
        effect:
          "Creates area of darkness, +50% damage in darkness for 8 seconds",
        description: "Garden blooms in eternal night, empowering attacks",
        target: "all-enemy",
        castTime: 3.8,
      },
    ],
  },
  "Crimson Thyra": {
    name: "Crimson Thyra",
    title: "Butterfly Soul Reaper",
    composition: {
      fire: 50,
      demon: 30,
      wind: 20,
    },
    abilities: [
      {
        name: "Soul Flame",
        emoji: "🔥",
        type: "quick",
        cooldown: 2,
        damage: 23,
        effect: "Burns for 6 damage over 3 seconds",
        description: "Dark fire that burns the soul itself",
        target: "single-enemy",
        castTime: 0.6,
      },
      {
        name: "Butterfly Swarm",
        emoji: "🦋",
        type: "power",
        cooldown: 8,
        damage: 32,
        effect: "Each enemy hit increases next ability damage by 10%",
        description: "Summons demonic butterflies that enhance power with each target struck",
        target: "all-enemy",
        castTime: 1.5,
      },
      {
        name: "Reaper's Wind",
        emoji: "🌀",
        type: "power",
        cooldown: 10,
        damage: 35,
        effect: "Damage increases based on enemy's current HP",
        description: "Wind that grows stronger against healthy enemies",
        target: "single-enemy",
        castTime: 1.9,
      },
      {
        name: "Soul Harvest",
        emoji: "💀",
        type: "ultimate",
        cooldown: 32,
        damage: 75,
        effect: "Deals 50% more damage if enemy below 30% HP",
        description: "Reaps weakened souls with devastating power",
        target: "single-enemy",
        castTime: 4,
      },
    ],
  },
};
