import { Ability, ElementComposition } from "./types";

// SoulBeast interface with typed name
export interface SoulBeast {
  name: string;
  title: string;
  composition: ElementComposition;
  abilities: readonly Ability[];
  image: string;
  configurations: readonly SoulbeastConfiguration[];
}

export interface SoulbeastConfiguration {
  name: string;
  description: string;
  abilities: readonly string[];
  totalCost: number;
}

export const AllSoulBeast = {
  "Keth Stalker": {
    name: "Keth Stalker",
    title: "Crystal Nightmare Hunter",
    image: "/img/cards/keth-stalker.webp",
    composition: {
      frost: 30,
      demon: 40,
      water: 30,
    },
    abilities: [
      {
        name: "Nightmare Frost",
        slug: "nightmare-frost",
        type: "quick",
        cooldown: 3,
        damage: 18,
        effect: "Applies slow for 2 seconds",
        description: "Channels demonic frost to slow and damage enemies.",
        target: "single-enemy",
        castTime: 0.8,
        soulshardCost: 2,
        activationConditions: [{ type: "on_available", priority: 1 }],
      },
      {
        name: "Crystal Prison",
        slug: "crystal-prison",
        type: "power",
        cooldown: 12,
        damage: 0,
        effect: "Stuns target for 2.5 seconds",
        description: "Traps enemy in crystalline ice, preventing actions.",
        target: "single-enemy",
        castTime: 1.8,
        soulshardCost: 5,
        activationConditions: [{ type: "on_available", priority: 8 }],
      },
      {
        name: "Abyssal Tide",
        slug: "abyssal-tide",
        type: "power",
        cooldown: 10,
        damage: 35,
        effect: "Heals self for 15 HP",
        description:
          "Summons dark waters that damage foes and restore vitality.",
        initiationTime: 3,
        target: "all-enemy",
        castTime: 2.2,
        soulshardCost: 5,
        activationConditions: [{ type: "on_own_hp_below", value: 50 }],
      },
      {
        name: "Nightmare Hunt",
        slug: "nightmare-hunt",
        type: "ultimate",
        cooldown: 25,
        damage: 60,
        effect: "Next 2 abilities have 50% reduced cooldown",
        description: "Enters a hunting frenzy, unleashing rapid attacks.",
        initiationTime: 8,
        target: "single-enemy",
        castTime: 3.5,
        soulshardCost: 8,
        activationConditions: [{ type: "on_available", priority: 10 }],
      },
      {
        name: "Demonic Haste",
        slug: "demonic-haste",
        type: "passive",
        cooldown: 0,
        damage: 0,
        effect: "Gain 20% evasion for 3 seconds after using an ability",
        description: "Demonic energy enhances your reflexes.",
        target: "self",
        castTime: 0,
        soulshardCost: 3,
        activationConditions: [{ type: "on_own_hp_below", value: 60 }],
      },
      {
        name: "Ice Shard",
        slug: "ice-shard",
        type: "quick",
        cooldown: 2,
        damage: 12,
        effect: "Lowers enemy's frost resistance.",
        description: "A quick shard of ice to soften the target.",
        target: "single-enemy",
        castTime: 0.5,
        soulshardCost: 1,
        activationConditions: [{ type: "on_available", priority: 2 }],
      },
      {
        name: "Glacial Armor",
        slug: "glacial-armor",
        type: "power",
        cooldown: 12,
        damage: 0,
        effect: "Reduces incoming damage by 30% for 5 seconds.",
        description: "Form a protective layer of demonic ice.",
        target: "self",
        castTime: 1.0,
        soulshardCost: 3,
        activationConditions: [{ type: "on_available", priority: 6 }],
      },
      {
        name: "Frozen Wake",
        slug: "frozen-wake",
        type: "power",
        cooldown: 14,
        damage: 28,
        effect: "Damages all enemies and applies minor slow for 5 seconds",
        description: "Leaves a trail of ice that hinders all foes.",
        target: "all-enemy",
        castTime: 2.2,
        soulshardCost: 6,
        activationConditions: [{ type: "on_available", priority: 6 }],
      },
      {
        name: "Permafrost",
        slug: "permafrost",
        type: "passive",
        cooldown: 0,
        damage: 0,
        effect: "Slow effects you apply last 1 second longer.",
        description: "Your chilling presence makes escape nearly impossible.",
        target: "self",
        castTime: 0,
        soulshardCost: 3,
        activationConditions: [{ type: "at_start" }],
      },
      {
        name: "Shatter",
        slug: "shatter",
        type: "power",
        cooldown: 10,
        damage: 50,
        effect: "Deals double damage to stunned or frozen targets.",
        description:
          "Exploit the enemy's compromised state with a shattering blow.",
        target: "single-enemy",
        castTime: 1.5,
        soulshardCost: 5,
        activationConditions: [
          { type: "after_ability_used", abilityName: "Crystal Prison" },
        ],
      },
    ],
    configurations: [
      {
        name: "Controller Build",
        description:
          "Focuses on slowing and stunning the enemy to control the flow of battle. Manual timing of Crystal Prison is key.",
        abilities: [
          "Nightmare Frost",
          "Ice Shard",
          "Crystal Prison",
          "Permafrost",
          "Shatter",
        ],
        totalCost: 15,
      },
      {
        name: "All-Out Offensive",
        description:
          "A high-risk, high-reward build centered around the ultimate ability.",
        abilities: [
          "Nightmare Hunt",
          "Ice Shard",
          "Shatter",
          "Nightmare Frost",
        ],
        totalCost: 16,
      },
      {
        name: "Sustained Damage",
        description:
          "A balanced build that combines damage with self-preservation. Use Glacial Armor manually for optimal defense.",
        abilities: [
          "Abyssal Tide",
          "Frozen Wake",
          "Glacial Armor",
          "Nightmare Frost",
          "Ice Shard",
        ],
        totalCost: 15,
      },
    ],
  },
  "Crimson Vorthak": {
    name: "Crimson Vorthak",
    title: "Bleeding Rose Executioner",
    image: "/img/cards/crimson-vorthak.webp",
    composition: { fire: 60, demon: 30, beast: 10 },
    abilities: [
      {
        name: "Flame Slash",
        slug: "flame-slash",
        type: "quick",
        cooldown: 2,
        damage: 22,
        effect: "Burns for 5 damage over 3 seconds",
        description: "Quick fiery strike that leaves burning wounds.",
        target: "single-enemy",
        castTime: 0.6,
        soulshardCost: 2,
        activationConditions: [{ type: "on_available", priority: 1 }],
      },
      {
        name: "Demonic Roar",
        slug: "demonic-roar",
        type: "power",
        cooldown: 9,
        damage: 15,
        effect: "Reduces enemy damage by 30% for 4 seconds",
        description: "Terrifying howl that weakens enemy resolve.",
        target: "all-enemy",
        castTime: 1.8,
        soulshardCost: 4,
        activationConditions: [{ type: "after_damage_taken" }],
      },
      {
        name: "Infernal Execution",
        slug: "infernal-execution",
        type: "power",
        cooldown: 12,
        damage: 45,
        effect: "Damage increases by 50% if enemy below 40% HP",
        description: "Devastating finisher attack against wounded foes.",
        initiationTime: 4,
        target: "single-enemy",
        castTime: 2.1,
        soulshardCost: 6,
        activationConditions: [{ type: "on_available", priority: 7 }],
      },
      {
        name: "Rose of Destruction",
        slug: "rose-of-destruction",
        type: "ultimate",
        cooldown: 30,
        damage: 70,
        effect: "Creates fire field that deals 10 damage/second for 5 seconds",
        description: "Blooms a deadly rose of fire that burns the battlefield.",
        initiationTime: 10,
        target: "all-enemy",
        castTime: 4.0,
        soulshardCost: 8,
        activationConditions: [{ type: "on_available", priority: 10 }],
      },
      {
        name: "Burning Blood",
        slug: "burning-blood",
        type: "passive",
        cooldown: 0,
        damage: 0,
        effect: "Take 5% less damage for each 10% health missing.",
        description:
          "As you get weaker, your demonic blood boils with defiance.",
        target: "self",
        castTime: 0,
        soulshardCost: 5,
        activationConditions: [{ type: "at_start" }],
      },
      {
        name: "Cauterize",
        slug: "cauterize",
        type: "quick",
        cooldown: 8,
        damage: 0,
        effect: "Heals for 20 HP but deals 5 damage to self.",
        description: "Sear your own wounds with fire to recover.",
        target: "self",
        castTime: 1.0,
        soulshardCost: 2,
        activationConditions: [{ type: "on_own_hp_below", value: 60 }],
      },
      {
        name: "Raging Beast",
        slug: "raging-beast",
        type: "power",
        cooldown: 10,
        damage: 0,
        effect: "Increases your damage output by 25% for 6 seconds.",
        description: "Unleash your inner beast for a surge of power.",
        target: "self",
        castTime: 1.2,
        soulshardCost: 3,
        activationConditions: [{ type: "on_available", priority: 8 }],
      },
      {
        name: "Scent of Blood",
        slug: "scent-of-blood",
        type: "passive",
        cooldown: 0,
        damage: 0,
        effect: "Gain 25% critical hit chance when enemy is below 40% HP",
        description: "The smell of blood drives you into a frenzy.",
        target: "self",
        castTime: 0,
        soulshardCost: 4,
        activationConditions: [{ type: "at_start" }],
      },
      {
        name: "Fire Wall",
        slug: "fire-wall",
        type: "power",
        cooldown: 16,
        damage: 35,
        effect: "Damages enemies that use quick abilities for 8 seconds",
        description: "Creates a barrier of flames that punishes hasty actions.",
        target: "all-enemy",
        castTime: 2.8,
        soulshardCost: 6,
        activationConditions: [{ type: "on_available", priority: 7 }],
      },
      {
        name: "Reckless Charge",
        slug: "reckless-charge",
        type: "power",
        cooldown: 10,
        damage: 50,
        effect: "Deal 12 damage to yourself",
        description: "A devastating attack that comes at a personal cost.",
        target: "single-enemy",
        castTime: 1.4,
        soulshardCost: 4,
        activationConditions: [{ type: "on_available", priority: 4 }],
      },
    ],
    configurations: [
      {
        name: "Executioner",
        description:
          "Wear down the enemy and then finish them with a powerful blow. Time Infernal Execution manually for maximum impact.",
        abilities: [
          "Flame Slash",
          "Scent of Blood",
          "Infernal Execution",
          "Reckless Charge",
        ],
        totalCost: 14,
      },
      {
        name: "Wounded Beast",
        description:
          "This build gets stronger as your health gets lower. Manually activate Raging Beast at the perfect moment.",
        abilities: [
          "Burning Blood",
          "Demonic Roar",
          "Cauterize",
          "Flame Slash",
          "Raging Beast",
        ],
        totalCost: 16,
      },
      {
        name: "Area Denial",
        description:
          "Control the battlefield with fire and punishing abilities.",
        abilities: [
          "Rose of Destruction",
          "Fire Wall",
          "Flame Slash",
          "Cauterize",
        ],
        totalCost: 16,
      },
    ],
  },
  "Bone Thurak": {
    name: "Bone Thurak",
    title: "Ancient Fire Caller",
    image: "/img/cards/bone-thurak.webp",
    composition: { earth: 50, fire: 30, demon: 20 },
    abilities: [
      {
        name: "Stone Shard",
        slug: "stone-shard",
        type: "quick",
        cooldown: 5,
        damage: 22,
        effect: "Reduces enemy damage by 20% for 4 seconds",
        description: "A sharp stone that weakens your foe.",
        target: "single-enemy",
        castTime: 0.9,
        soulshardCost: 3,
        activationConditions: [{ type: "on_available", priority: 2 }],
      },
      {
        name: "Molten Boulder",
        slug: "molten-boulder",
        type: "power",
        cooldown: 9,
        damage: 40,
        effect: "40% chance to daze target for 2.5 seconds",
        description: "A massive rock heated by inner fire.",
        target: "single-enemy",
        castTime: 2.0,
        soulshardCost: 5,
        activationConditions: [{ type: "on_available", priority: 3 }],
      },
      {
        name: "Bone Armor",
        slug: "bone-armor",
        type: "power",
        cooldown: 15,
        damage: 0,
        effect: "Reduce incoming damage by 35% for 8 seconds",
        description: "Surround yourself with protective bone fragments.",
        target: "self",
        castTime: 1.8,
        soulshardCost: 5,
        activationConditions: [{ type: "on_own_hp_below", value: 70 }],
      },
      {
        name: "Ancient Eruption",
        slug: "ancient-eruption",
        type: "ultimate",
        cooldown: 30,
        damage: 75,
        effect: "Creates lava pools that deal damage over time for 10 seconds",
        description: "Unleash the fury of ancient volcanic power.",
        initiationTime: 10,
        target: "all-enemy",
        castTime: 4.0,
        soulshardCost: 9,
        activationConditions: [{ type: "on_available", priority: 10 }],
      },
      {
        name: "Fossilize",
        slug: "fossilize",
        type: "passive",
        cooldown: 0,
        damage: 0,
        effect:
          "Gain 20% damage reduction permanently after falling below 60% HP once.",
        description: "Your hide hardens like ancient stone when near death.",
        target: "self",
        castTime: 0,
        soulshardCost: 4,
        activationConditions: [{ type: "after_damage_taken" }],
      },
      {
        name: "Earthquake",
        slug: "earthquake",
        type: "power",
        cooldown: 12,
        damage: 30,
        effect: "Slows all enemies and reduces their armor.",
        description: "Shake the very ground to disrupt and weaken all foes.",
        target: "all-enemy",
        castTime: 2.5,
        soulshardCost: 5,
        activationConditions: [{ type: "on_enemy_hp_above", value: 75 }],
      },
      {
        name: "Magma Spit",
        slug: "magma-spit",
        type: "quick",
        cooldown: 4,
        damage: 15,
        effect: "Applies a burn that deals damage over time.",
        description: "Spit molten rock that clings and burns.",
        target: "single-enemy",
        castTime: 0.6,
        soulshardCost: 2,
        activationConditions: [{ type: "on_available", priority: 2 }],
      },
      {
        name: "Petrifying Gaze",
        slug: "petrifying-gaze",
        type: "power",
        cooldown: 15,
        damage: 10,
        effect: "Enemy is slowed by 50% for 3 seconds.",
        description:
          "A demonic gaze that turns flesh to stone, hindering actions.",
        target: "single-enemy",
        castTime: 1.8,
        soulshardCost: 3,
        activationConditions: [{ type: "after_enemy_dodges" }],
      },
      {
        name: "Demonic Core",
        slug: "demonic-core",
        type: "passive",
        cooldown: 0,
        damage: 0,
        effect:
          "After usning fire abilities (Molten Boulder, Ancient Eruption, Magma Spit) heal for 12 HP.",
        description:
          "A demonic heart that thrives on destruction, converting flames to vitality.",
        target: "self",
        castTime: 0,
        soulshardCost: 4,
        activationConditions: [
          {
            type: "after_ability_used",
          },
        ],
      },
      {
        name: "Unearth",
        slug: "unearth",
        type: "power",
        cooldown: 20,
        damage: 0,
        effect: "Resets the cooldown of your non-ultimate abilities.",
        description:
          "Dig deep into your ancient power to ready your skills once more.",
        target: "self",
        castTime: 3.0,
        soulshardCost: 6,
        activationConditions: [{ type: "on_own_hp_above", value: 80 }],
      },
    ],
    configurations: [
      {
        name: "Unkillable Tank",
        description:
          "A build focused on extreme survivability through damage reduction. Manual Bone Armor timing is crucial.",
        abilities: [
          "Molten Boulder",
          "Magma Spit",
          "Fossilize",
          "Demonic Core",
        ],
        totalCost: 15,
      },
      {
        name: "Area Control",
        description: "Dominate the battlefield with area-of-effect abilities.",
        abilities: ["Ancient Eruption", "Earthquake", "Stone Shard"],
        totalCost: 15,
      },
      {
        name: "Relentless Assault",
        description:
          "Never let up the pressure by constantly refreshing your abilities.",
        abilities: ["Unearth", "Molten Boulder", "Stone Shard", "Magma Spit"],
        totalCost: 14,
      },
    ],
  },
  "Shrom Xelar": {
    name: "Shrom Xelar",
    title: "Psychic Mushroom Axelar",
    image: "/img/cards/shrom-xelar.webp",
    composition: { nature: 60, beast: 30, demon: 10 },
    abilities: [
      {
        name: "Spore Burst",
        slug: "spore-burst",
        type: "quick",
        cooldown: 4,
        damage: 18,
        effect: "40% chance to poison target for 5 seconds",
        description: "Release toxic spores that may poison your foe.",
        target: "single-enemy",
        castTime: 0.9,
        soulshardCost: 2,
        activationConditions: [{ type: "on_available", priority: 1 }],
      },
      {
        name: "Mycelium Network",
        slug: "mycelium-network",
        type: "power",
        cooldown: 9,
        damage: 28,
        effect: "Damages all enemies, damage increases per target hit",
        description: "Underground fungal network damages connected foes.",
        target: "all-enemy",
        castTime: 2.4,
        soulshardCost: 5,
        activationConditions: [{ type: "on_available", priority: 5 }],
      },
      {
        name: "Soul Absorb",
        slug: "soul-absorb",
        type: "power",
        cooldown: 12,
        damage: 30,
        effect: "Heal 20 HP and gain 15% damage boost for 10 seconds",
        description: "Drain the essence of your foe to empower yourself.",
        target: "single-enemy",
        castTime: 1.8,
        soulshardCost: 5,
        activationConditions: [{ type: "on_available", priority: 5 }],
      },
      {
        name: "Fungal Nightmare",
        slug: "fungal-nightmare",
        type: "ultimate",
        cooldown: 30,
        damage: 70,
        effect:
          "Causes hallucinations, enemy attacks random targets for 6 seconds",
        description: "Psychedelic spores invade enemy mind, causing chaos.",
        initiationTime: 12,
        target: "single-enemy",
        castTime: 3.6,
        soulshardCost: 8,
        activationConditions: [{ type: "on_available", priority: 10 }],
      },
      {
        name: "Toxic Aura",
        slug: "toxic-aura",
        type: "power",
        cooldown: 15,
        damage: 0,
        effect: "Poisons all enemies for 8 seconds",
        description: "Emit a cloud of toxic spores that affects all foes.",
        target: "all-enemy",
        castTime: 2.3,
        soulshardCost: 6,
        activationConditions: [{ type: "on_available", priority: 7 }],
      },
      {
        name: "Rapid Growth",
        slug: "rapid-growth",
        type: "power",
        cooldown: 10,
        damage: 0,
        effect: "Heal 40 HP over 5 seconds",
        description: "Channel natural energy to rapidly regenerate.",
        target: "self",
        castTime: 1.5,
        soulshardCost: 4,
        activationConditions: [{ type: "on_own_hp_below", value: 60 }],
      },
      {
        name: "Hallucinogenic Haze",
        slug: "hallucinogenic-haze",
        type: "power",
        cooldown: 14,
        damage: 10,
        effect: "Reduces enemy accuracy by 30% for 5 seconds.",
        description:
          "Release a confusing haze that makes it hard for enemies to land attacks.",
        target: "all-enemy",
        castTime: 2.0,
        soulshardCost: 4,
        activationConditions: [{ type: "after_damage_taken" }],
      },
      {
        name: "Parasitic Spore",
        slug: "parasitic-spore",
        type: "quick",
        cooldown: 5,
        damage: 15,
        effect: "If the target dies while this is active, you heal for 25 HP.",
        description: "A spore that leeches life from the host upon its death.",
        target: "single-enemy",
        castTime: 0.8,
        soulshardCost: 2,
        activationConditions: [{ type: "on_enemy_hp_below", value: 30 }],
      },
      {
        name: "Symbiosis",
        slug: "symbiosis",
        type: "passive",
        cooldown: 0,
        damage: 0,
        effect:
          "Your healing abilities also deal 25% of the healed amount as damage to a random enemy.",
        description: "The life you gain is taken from another.",
        target: "self",
        castTime: 0,
        soulshardCost: 4,
        activationConditions: [{ type: "at_start" }],
      },
      {
        name: "Decompose",
        slug: "decompose",
        type: "power",
        cooldown: 11,
        damage: 20,
        effect: "Reduces enemy armor by 40% for 8 seconds.",
        description: "Break down the enemy's defenses, making them vulnerable.",
        target: "single-enemy",
        castTime: 1.7,
        soulshardCost: 3,
        activationConditions: [{ type: "on_enemy_hp_above", value: 90 }],
      },
    ],
    configurations: [
      {
        name: "Poison Master",
        description:
          "Focus on whittling down the enemy with poison and debuffs.",
        abilities: [
          "Spore Burst",
          "Toxic Aura",
          "Hallucinogenic Haze",
          "Decompose",
          "Parasitic Spore",
        ],
        totalCost: 16,
      },
      {
        name: "Life-Leecher",
        description:
          "A durable build that out-sustains the opponent through healing. Manual Soul Absorb for strategic life steal.",
        abilities: ["Soul Absorb", "Rapid Growth", "Symbiosis", "Spore Burst"],
        totalCost: 15,
      },
      {
        name: "Chaos Controller",
        description:
          "Disrupt the enemy's strategy with powerful, mind-altering abilities.",
        abilities: ["Fungal Nightmare", "Hallucinogenic Haze", "Spore Burst"],
        totalCost: 14,
      },
    ],
  },
  "Void Ghorth": {
    name: "Void Ghorth",
    title: "Dimensional Terror Beast",
    image: "/img/cards/void-ghorth.webp",
    composition: { water: 50, beast: 40, demon: 10 },
    abilities: [
      {
        name: "Savage Splash",
        slug: "savage-splash",
        type: "quick",
        cooldown: 3,
        damage: 19,
        effect: "Heals self for 8 HP",
        description: "Bestial attack that splashes healing waters.",
        target: "single-enemy",
        castTime: 0.7,
        soulshardCost: 2,
        activationConditions: [{ type: "on_available", priority: 1 }],
      },
      {
        name: "Dimensional Bite",
        slug: "dimensional-bite",
        type: "power",
        cooldown: 9,
        damage: 35,
        effect: "Ignores 100% of enemy armor",
        description: "Phases through dimensions to deliver a devastating bite.",
        initiationTime: 3,
        target: "single-enemy",
        castTime: 2.1,
        soulshardCost: 5,
        activationConditions: [{ type: "on_available", priority: 11 }],
      },
      {
        name: "Terror Howl",
        slug: "terror-howl",
        type: "power",
        cooldown: 11,
        damage: 20,
        effect: "Reduces enemy damage output by 50% for 3 seconds",
        description: "Horrifying roar that terrifies and weakens enemies.",
        target: "all-enemy",
        castTime: 1.7,
        soulshardCost: 4,
        activationConditions: [{ type: "after_damage_taken" }],
      },
      {
        name: "Void Tsunami",
        slug: "void-tsunami",
        type: "ultimate",
        cooldown: 26,
        damage: 75,
        effect: "Creates void zones that deal 12 damage/second",
        description: "Summons dimensional water that tears reality apart.",
        initiationTime: 10,
        target: "all-enemy",
        castTime: 3.2,
        soulshardCost: 8,
        activationConditions: [{ type: "on_available", priority: 10 }],
      },
      {
        name: "Phase Shift",
        slug: "phase-shift",
        type: "passive",
        cooldown: 0,
        damage: 0,
        effect: "20% chance to evade any incoming attack.",
        description:
          "Your body flickers between dimensions, making you hard to hit.",
        target: "self",
        castTime: 0,
        soulshardCost: 6,
        activationConditions: [{ type: "at_start" }],
      },
      {
        name: "Aqua Jet",
        slug: "aqua-jet",
        type: "quick",
        cooldown: 4,
        damage: 22,
        effect: "High priority, almost always goes first.",
        description: "Propel yourself with a jet of water for a swift strike.",
        target: "single-enemy",
        castTime: 0.4,
        soulshardCost: 2,
        activationConditions: [{ type: "on_available", priority: 0 }],
      },
      {
        name: "Regenerative Torpor",
        slug: "regenerative-torpor",
        type: "power",
        cooldown: 15,
        damage: 0,
        effect: "Heals 40% of max HP over 5 seconds, but you are slowed.",
        description: "Enter a deep, regenerative state to recover from wounds.",
        target: "self",
        castTime: 2.0,
        soulshardCost: 5,
        activationConditions: [{ type: "on_own_hp_below", value: 30 }],
      },
      {
        name: "Unstable Rift",
        slug: "unstable-rift",
        type: "power",
        cooldown: 12,
        damage: 30,
        effect: "Confuses target, reducing accuracy by 40% for 4 seconds.",
        description: "Tear a hole in reality that disorients your foe.",
        target: "single-enemy",
        castTime: 2.2,
        soulshardCost: 4,
        activationConditions: [{ type: "on_enemy_hp_above", value: 80 }],
      },
      {
        name: "Beast of the Depths",
        slug: "beast-of-the-depths",
        type: "passive",
        cooldown: 0,
        damage: 0,
        effect: "Gain 1% damage for every 2% HP you are missing.",
        description: "The more wounded you are, the more ferocious you become.",
        target: "self",
        castTime: 0,
        soulshardCost: 4,
        activationConditions: [{ type: "at_start" }],
      },
      {
        name: "Drown",
        slug: "drown",
        type: "power",
        cooldown: 10,
        damage: 15,
        effect: "Prevents the enemy from using abilities for 2 seconds.",
        description: "Flood the enemy's senses, silencing their powers.",
        target: "single-enemy",
        castTime: 1.5,
        soulshardCost: 3,
        activationConditions: [
          { type: "after_ability_used", abilityName: "Savage Splash" },
        ],
      },
    ],
    configurations: [
      {
        name: "Evasive Bruiser",
        description:
          "A hard-to-hit brawler that excels at surviving and dealing consistent damage. Manual Dimensional Bite for armor piercing.",
        abilities: [
          "Phase Shift",
          "Savage Splash",
          "Dimensional Bite",
          "Drown",
        ],
        totalCost: 16,
      },
      {
        name: "Wounded Animal",
        description:
          "The lower your health, the more dangerous you become. A high-risk build.",
        abilities: [
          "Beast of the Depths",
          "Regenerative Torpor",
          "Savage Splash",
          "Dimensional Bite",
        ],
        totalCost: 16,
      },
      {
        name: "Dimensional Controller",
        description:
          "Control the battlefield through dimensional manipulation and terror tactics.",
        abilities: ["Unstable Rift", "Terror Howl", "Drown", "Savage Splash"],
        totalCost: 14,
      },
    ],
  },
  "Deep Zephyros": {
    name: "Deep Zephyros",
    title: "Abyssal Mind Breaker",
    image: "/img/cards/deep-zephyros.webp",
    composition: { water: 40, beast: 30, demon: 30 },
    abilities: [
      {
        name: "Mind Lash",
        slug: "mind-lash",
        type: "quick",
        cooldown: 4,
        damage: 24,
        effect: "Reduces enemy accuracy by 30% for 5 seconds",
        description: "Psychic attack that disrupts enemy focus.",
        target: "single-enemy",
        castTime: 0.9,
        soulshardCost: 3,
        activationConditions: [{ type: "on_available", priority: 1 }],
      },
      {
        name: "Bestial Surge",
        slug: "bestial-surge",
        type: "power",
        cooldown: 12,
        damage: 0,
        effect: "Increases attack speed by 35% for 6 seconds.",
        description: "Channels primal instincts for rapid attacks.",
        target: "self",
        castTime: 1.8,
        soulshardCost: 4,
        activationConditions: [{ type: "on_available", priority: 12 }],
      },
      {
        name: "Abyssal Drain",
        slug: "abyssal-drain",
        type: "power",
        cooldown: 10,
        damage: 32,
        effect: "Steals 20 HP from enemy",
        description: "Drains life force through demonic waters.",
        initiationTime: 3,
        target: "single-enemy",
        castTime: 2.0,
        soulshardCost: 5,
        activationConditions: [{ type: "on_own_hp_below", value: 60 }],
      },
      {
        name: "Mind Break",
        slug: "mind-break",
        type: "ultimate",
        cooldown: 28,
        damage: 70,
        effect: "Enemy abilities have double cooldown for 10 seconds",
        description: "Shatters enemy psyche, disrupting their abilities.",
        initiationTime: 10,
        target: "single-enemy",
        castTime: 3.8,
        soulshardCost: 9,
        activationConditions: [{ type: "on_available", priority: 10 }],
      },
      {
        name: "Psychic Barrier",
        slug: "psychic-barrier",
        type: "passive",
        cooldown: 0,
        damage: 0,
        effect: "Once per battle, negate a debuff applied to you.",
        description:
          "A constant mental shield protects you from harmful effects.",
        target: "self",
        castTime: 0,
        soulshardCost: 4,
        activationConditions: [{ type: "at_start" }],
      },
      {
        name: "Tidal Slash",
        slug: "tidal-slash",
        type: "quick",
        cooldown: 4,
        damage: 25,
        effect: "Pushes the enemy back.",
        description: "A blade of water that creates distance.",
        target: "single-enemy",
        castTime: 0.9,
        soulshardCost: 2,
        activationConditions: [{ type: "on_available", priority: 2 }],
      },
      {
        name: "Demon's Guile",
        slug: "demons-guile",
        type: "power",
        cooldown: 12,
        damage: 0,
        effect: "Gain 100% evasion for 3 seconds.",
        description: "Use demonic power to become untouchable.",
        target: "self",
        castTime: 1.0,
        soulshardCost: 4,
        activationConditions: [{ type: "on_available", priority: 13 }],
      },
      {
        name: "Mental Fog",
        slug: "mental-fog",
        type: "power",
        cooldown: 15,
        damage: 15,
        effect: "All enemies are silenced for 1.5 seconds.",
        description:
          "A psychic fog that clouds thoughts and prevents ability use.",
        target: "all-enemy",
        castTime: 2.5,
        soulshardCost: 5,
        activationConditions: [{ type: "on_enemy_hp_above", value: 80 }],
      },
      {
        name: "Calamity Howl",
        slug: "calamity-howl",
        type: "power",
        cooldown: 11,
        damage: 28,
        effect: "Fears the target for 2 seconds, making them run away.",
        description: "A bestial howl that instills deep terror.",
        target: "single-enemy",
        castTime: 1.8,
        soulshardCost: 4,
        activationConditions: [{ type: "after_damage_taken" }],
      },
      {
        name: "Mind Reader",
        slug: "mind-reader",
        type: "passive",
        cooldown: 0,
        damage: 0,
        effect: "Gain 20% increased evasion against enemies with active buffs.",
        description: "Anticipate your foe's actions when they are empowered.",
        target: "self",
        castTime: 0,
        soulshardCost: 3,
        activationConditions: [{ type: "at_start" }],
      },
    ],
    configurations: [
      {
        name: "Psionic Duelist",
        description:
          "A disruptive fighter that focuses on controlling a single target.",
        abilities: ["Mind Break", "Mind Lash", "Calamity Howl", "Tidal Slash"],
        totalCost: 16,
      },
      {
        name: "Eldritch Survivor",
        description:
          "An evasive build that outlasts opponents with lifesteal and protection.",
        abilities: [
          "Abyssal Drain",
          "Psychic Barrier",
          "Demon's Guile",
          "Mind Lash",
        ],
        totalCost: 15,
      },
      {
        name: "Pack Hunter",
        description:
          "Focuses on speed and aggression to overwhelm the enemy. Manual Bestial Surge and Demon's Guile for tactical advantage.",
        abilities: [
          "Bestial Surge",
          "Tidal Slash",
          "Mind Lash",
          "Calamity Howl",
          "Demon's Guile",
        ],
        totalCost: 16,
      },
    ],
  },
  Astrix: {
    name: "Astrix",
    title: "Starbound Void Walker",
    image: "/img/cards/astrix.webp",
    composition: { demon: 40, divine: 30, wind: 30 },
    abilities: [
      {
        name: "Void Wind",
        slug: "void-wind",
        type: "quick",
        cooldown: 3,
        damage: 25,
        effect: "Ignores 100% of enemy armor",
        description: "Wind infused with void energy that bypasses armor.",
        target: "single-enemy",
        castTime: 1.0,
        soulshardCost: 3,
        activationConditions: [{ type: "on_available", priority: 1 }],
      },
      {
        name: "Divine Punishment",
        slug: "divine-punishment",
        type: "power",
        cooldown: 11,
        damage: 45,
        effect: "+100% damage vs demon enemies",
        description: "Holy power that especially harms demonic foes.",
        initiationTime: 4,
        target: "single-enemy",
        castTime: 1.8,
        soulshardCost: 6,
        activationConditions: [{ type: "on_available", priority: 5 }],
      },
      {
        name: "Stellar Dash",
        slug: "stellar-dash",
        type: "power",
        cooldown: 7,
        damage: 25,
        effect: "Becomes invulnerable during cast",
        description: "Moves at light speed, avoiding all attacks.",
        target: "single-enemy",
        castTime: 2.1,
        soulshardCost: 4,
        activationConditions: [{ type: "on_available", priority: 14 }],
      },
      {
        name: "Paradox Storm",
        slug: "paradox-storm",
        type: "ultimate",
        cooldown: 32,
        damage: 80,
        effect: "Deals divine damage to demons, demon damage to divine",
        description: "Creates a storm of contradictory energies.",
        initiationTime: 14,
        target: "all-enemy",
        castTime: 3.6,
        soulshardCost: 10,
        activationConditions: [{ type: "on_available", priority: 10 }],
      },
      {
        name: "Cosmic Balance",
        slug: "cosmic-balance",
        type: "passive",
        cooldown: 0,
        damage: 0,
        effect:
          "When you deal Divine damage, gain a shield. When you deal Demon damage, gain lifesteal.",
        description: "Harness both polarities for defense and offense.",
        target: "self",
        castTime: 0,
        soulshardCost: 5,
        activationConditions: [{ type: "at_start" }],
      },
      {
        name: "Starfall",
        slug: "starfall",
        type: "quick",
        cooldown: 5,
        damage: 18,
        effect: "Hits 3 times.",
        description: "Call down a volley of small meteorites.",
        target: "single-enemy",
        castTime: 1.2,
        soulshardCost: 2,
        activationConditions: [{ type: "on_available", priority: 2 }],
      },
      {
        name: "Void Jaunt",
        slug: "void-jaunt",
        type: "power",
        cooldown: 10,
        damage: 0,
        effect: "Clear all debuffs and gain brief invulnerability.",
        description: "Step through the void to purify yourself and avoid harm.",
        target: "self",
        castTime: 0.5,
        soulshardCost: 3,
        activationConditions: [{ type: "on_available", priority: 15 }],
      },
      {
        name: "Zephyr's Blessing",
        slug: "zephyrs-blessing",
        type: "power",
        cooldown: 12,
        damage: 0,
        effect: "Increases your attack speed and evasion by 25%.",
        description: "A divine wind hastens your actions.",
        target: "self",
        castTime: 1.0,
        soulshardCost: 3,
        activationConditions: [{ type: "on_own_hp_above", value: 80 }],
      },
      {
        name: "Gravity Well",
        slug: "gravity-well",
        type: "power",
        cooldown: 14,
        damage: 20,
        effect: "Slows all enemies and reduces their damage output.",
        description: "Manipulate gravity to weaken and hinder your foes.",
        target: "all-enemy",
        castTime: 2.0,
        soulshardCost: 4,
        activationConditions: [{ type: "on_enemy_hp_above", value: 70 }],
      },
      {
        name: "Entropic Touch",
        slug: "entropic-touch",
        type: "passive",
        cooldown: 0,
        damage: 0,
        effect:
          "Your attacks have a chance to reduce the duration of enemy buffs.",
        description: "Your demonic touch unravels enemy enchantments.",
        target: "self",
        castTime: 0,
        soulshardCost: 4,
        activationConditions: [{ type: "at_start" }],
      },
    ],
    configurations: [
      {
        name: "Glass Cannon",
        description:
          "An all-out offensive build focused on dealing massive, armor-piercing damage.",
        abilities: [
          "Void Wind",
          "Divine Punishment",
          "Starfall",
          "Zephyr's Blessing",
        ],
        totalCost: 13,
      },
      {
        name: "Balanced Paradox",
        description:
          "Utilizes both Divine and Demonic aspects for a versatile and resilient build.",
        abilities: ["Paradox Storm", "Cosmic Balance", "Void Wind"],
        totalCost: 16,
      },
      {
        name: "Manual Mastery",
        description:
          "A high-skill build focused on manual ability timing for maximum control and impact.",
        abilities: ["Stellar Dash", "Void Jaunt", "Void Wind", "Starfall"],
        totalCost: 12,
      },
      {
        name: "Evasive Striker",
        description:
          "A slippery build that uses evasion and invulnerability to outplay opponents. Manual Stellar Dash for perfect invulnerability timing.",
        abilities: [
          "Stellar Dash",
          "Void Jaunt",
          "Void Wind",
          "Zephyr's Blessing",
          "Starfall",
        ],
        totalCost: 15,
      },
    ],
  },
} as const;

// Export the typed name after AllSoulBeast is defined
export type SoulBeastName = keyof typeof AllSoulBeast;
